server:
  port: 10000

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karmanov/zambeex
          search-paths: config